%% Parameters
Iph=1860;% in A % phase current rms
length=0.925*600;     % in m % Total copper length in active region
total_height=61.4e-3; % in m % slot copper height for single copper
insulation=0.21e-3;   % in m % strand-to-strand insulation length
total_width=16e-3;    % in m % total copper width 
numberOfhorizontalStrand=2; % number of  horizontal strands 
width_strand=7.69e-3; % in m % strand width 
ro=2.0968e-8;         % in Ohm*m  % resistivity at 125 degree
k=2.4;                % unitless % (endwinding+active)/active region ratio 
mu0=4*pi*1e-7;        % permeability
f=50;                 % in 1/s % frequency of the current

%% Arrays
height_strand_X=[];  % in m  % array recording different strand heights 
                     % according to number of vertical...
                     % strands and slot copper height for single copper
Pdc_tot=[];          % in kW % Total DC loss consisting both top and 
                     % bottom windings
P_eddy_tot=[];       % in kW % Total Eddy loss consisting both top and
                     % bottom windings.  Not include circulation current 
                     % which is eliminated by roebel transposition
strand=[];           % array recording the number of vertical strands 
                     % numberOfverticalStrand
TopBottom=[];        % Eddy losses ratio of top to bottom coils

for numberOfverticalStrand=6:1:66 % indexing number of vertical strands  
 
Bmax=(2*mu0*Iph)/(total_width); % Maximum tangential B, generated by coils
                                % We have two coils, called top and bottom
                                % Top coil is the coil close to airgap
                                % Bottom coil is the coil far away from 
                                % to airgap
                                
B=linspace(0,Bmax,numberOfverticalStrand*2); % B for each strand 
                             % First half of the array belongs to top   
                             % Latter half of the array belongs to bottom 


Ke= pi^2/(6*ro);                % The constant for eddy losses

height_strand=(total_height/numberOfverticalStrand)-insulation;
                                % the height for strand according to 
                                % strand number

DC_resistance=ro*length*k/((width_strand*height_strand)); 
                                % DC resistance for unit area included both
                                % active and endwinding region
                                % for both top and bottom coil
DC_resistance=DC_resistance/(numberOfverticalStrand*numberOfhorizontalStrand);
                                % DC resistance for unit area included both
                                % active and endwinding region
                                % for both top and bottom coil
                                                              
Pdc=Iph^2*DC_resistance;        % DC losses for the indexed strand


volume=2*width_strand*height_strand*length; 
                                % strand volume for each vertical level
                                % included 2 horizontal strand

Peddy= Ke*B.^2*f^2*height_strand^2*volume;
                                % Eddy losses for each vertical level

Pdc_tot=[Pdc_tot Pdc];               % Total DC losses for the
                                     % indexed strand number

P_eddy_tot=[P_eddy_tot sum(Peddy)];  % Total Eddy losses for the
                                     % indexed strand number

                                     
TopBottom=[TopBottom ...
    sum(Peddy(1:numberOfverticalStrand/2))/...
    sum(Peddy(numberOfverticalStrand/2+1:end))];
                                     % Eddy losses ratio of top 
                                     % to bottom coils
                
strand=[strand numberOfverticalStrand]; 
                       % array recording the number of vertical strands 
                       % numberOfverticalStrand
height_strand_X=[height_strand_X height_strand];
                     % in m  % array recording different strand heights 
                     % according to number of vertical...
                     % strands and slot copper height for single copper

end
%%
figure1 = figure;
axes1 = axes('Parent',figure1);
hold(axes1,'on');
yyaxis(axes1,'left');
plot(strand,(P_eddy_tot+Pdc_tot)/Pdc_tot(1),'LineStyle',"-",'Color','k' ...
    ,'Marker','x','MarkerSize',10,'MarkerFaceColor','k');
ylabel('DC+Strand Losses (p.u) ')
hold on;
set(axes1,'YColor',[0 0 0]);
yyaxis(axes1,'right');
plot(strand,1000*height_strand_X,'LineStyle',"-",'Color','b' ...
    ,'Marker','x','MarkerSize',10,'MarkerFaceColor','b');
ylabel('Strand Height (mm)')
hold on;
set(axes1,'YColor',[0 0 1]);
xlabel('Vertical Strands')
ax = gca; % current axes
ax.FontSize = 15;
ax.FontName= 'Times New Roman';
%yticks(0:0.2:1)
xlim([6 numberOfverticalStrand])
xticks(6:3:numberOfverticalStrand)
% ylim([0 1])
grid on;
% grid minor;
%%
figure1 = figure;
axes1 = axes('Parent',figure1);
hold(axes1,'on');
yyaxis(axes1,'left');
plot(strand,(P_eddy_tot)/Pdc_tot(1),'LineStyle',"-",'Color','k' ...
    ,'Marker','x','MarkerSize',10,'MarkerFaceColor','k');
ylabel('AC resistance(p.u) ')
hold on;
set(axes1,'YColor',[0 0 0]);
yyaxis(axes1,'right');
plot(strand,1000*height_strand_X,'LineStyle',"-",'Color','b' ...
    ,'Marker','x','MarkerSize',10,'MarkerFaceColor','b');
ylabel('Strand Height (mm)')
hold on;
set(axes1,'YColor',[0 0 1]);
xlabel('Vertical Strands')
ax = gca; % current axes
ax.FontSize = 15;
ax.FontName= 'Times New Roman';
%yticks(0:0.2:1)
xlim([6 numberOfverticalStrand])
xticks(6:3:numberOfverticalStrand)
% ylim([0 1])
grid on;
% grid minor;
%%
figure1 = figure;
axes1 = axes('Parent',figure1);
hold(axes1,'on');
yyaxis(axes1,'left');
plot(strand,(Pdc_tot)/Pdc_tot(1),'LineStyle',"-",'Color','k' ...
    ,'Marker','x','MarkerSize',10,'MarkerFaceColor','k');
ylabel('DC resistance(p.u) ')
hold on;
set(axes1,'YColor',[0 0 0]);
yyaxis(axes1,'right');
plot(strand,1000*height_strand_X,'LineStyle',"-",'Color','b' ...
    ,'Marker','x','MarkerSize',10,'MarkerFaceColor','b');
ylabel('Strand Height (mm)')
hold on;
set(axes1,'YColor',[0 0 1]);
xlabel('Vertical Strands')
ax = gca; % current axes
ax.FontSize = 15;
ax.FontName= 'Times New Roman';
%yticks(0:0.2:1)
xlim([6 numberOfverticalStrand])
xticks(6:3:numberOfverticalStrand)
% ylim([0 1])
grid on;
% grid minor;




